'use strict';
const API='https://msbt-community-library.screename53.workers.dev', $=id=>document.getElementById(id), contract=communityFolderContract;
let prepared=null,shown=0,busy=false;
const node=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;return el;};
const database=new Promise((resolve,reject)=>{const req=indexedDB.open('community-submissions',1);req.onupgradeneeded=()=>req.result.createObjectStore('submissions',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Browser storage is unavailable. Enable site storage before submitting.'));});
async function storage(method,value){const db=await database;return new Promise((resolve,reject)=>{const tx=db.transaction('submissions',method==='getAll'?'readonly':'readwrite'),request=tx.objectStore('submissions')[method](...(value===undefined?[]:[value]));tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(Error('Could not save your submission on this browser. Nothing new was uploaded.'));});}
async function run(fn){if(busy)return;busy=true;$('fields').disabled=true;try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;$('fields').disabled=false;}}
function invalidate(){prepared=null;$('preview').hidden=true;$('consent').checked=false;}
for(const id of ['title','creator','description','source'])$(id).addEventListener('input',invalidate);
$('file').onchange=()=>run(async()=>{invalidate();const file=$('file').files[0];if(!file)return;if(file.size>contract.MAX_BYTES)throw Error('File exceeds 16 MB. Split it into smaller collections.');$('source').value=await file.text();$('message').textContent='File loaded. Choose Preview loadout.';});
$('previewButton').onclick=()=>run(async()=>{
 invalidate();const text=$('source').value.trim();if(new TextEncoder().encode(text).length>contract.MAX_BYTES)throw Error('Input exceeds 16 MB.');let folder;
 if(text.startsWith('{')){const data=JSON.parse(text);folder=data.folder||data;for(const key of ['title','creator','description'])if(!$(key).value&&typeof folder[key]==='string')$(key).value=folder[key];}
 else folder={version:1,folders:[],items:text.split(/\r?\n/).filter(line=>line.trim()).map((serial,i)=>({name:'Saved item '+(i+1),folder:'',serial:serial.trim()}))};
 prepared=contract.normalize({...folder,title:$('title').value,creator:$('creator').value,description:$('description').value});shown=0;$('items').replaceChildren();render();$('preview').hidden=false;$('message').textContent='Review the names and codes below before submitting.';
});
function render(){const end=Math.min(shown+50,prepared.items.length);for(let i=shown;i<end;i++){const item=prepared.items[i],row=node('div','');row.className='item';const label=node('label','Item '+(i+1)+' name'),input=document.createElement('input');input.value=item.name;input.maxLength=180;input.oninput=()=>{item.name=input.value;$('consent').checked=false;};label.append(input);const code=document.createElement('textarea');code.readOnly=true;code.value=item.serial;code.setAttribute('aria-label','Item '+(i+1)+' code');row.append(label,node('small',item.folder||'Folder root'),code);$('items').append(row);}shown=end;$('count').textContent=prepared.items.length+' items · showing '+shown;$('more').hidden=shown>=prepared.items.length;}
$('more').onclick=()=>{if(!busy)render();};
async function request(record,method){const res=await fetch(API+'/submissions'+(method==='POST'?'':'/'+record.id),{method,credentials:'omit',redirect:'error',headers:{Authorization:'Bearer '+record.secret,...(method==='POST'?{'Content-Type':'application/json'}:{})},body:method==='POST'?JSON.stringify({id:record.id,folder:record.folder}):undefined,signal:AbortSignal.timeout(60000)});const data=await res.json();if(!res.ok||!data.ok)throw Error(data.message||'Request failed.');return data;}
async function send(record){$('message').textContent='Uploading for review…';const data=await request(record,'POST');record.status=data.status;delete record.folder;await storage('put',record);$('message').textContent='Submitted for approval. It will appear in the library after a reviewer approves it.';}
$('form').onsubmit=e=>{e.preventDefault();run(async()=>{if(!prepared)throw Error('Preview your loadout first.');if(!$('consent').checked)throw Error('Confirm that you want to share this loadout.');const record={id:crypto.randomUUID(),secret:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),folder:contract.normalize(prepared),title:prepared.title,status:'sending'};await storage('put',record);invalidate();try{await send(record);$('form').reset();}catch(e){throw Error(e.message+' Use Retry below to safely finish this same submission.');}finally{await mine();}});};
async function mine(){const records=await storage('getAll');$('mine').replaceChildren();if(!records.length)$('mine').append(node('p','No submissions saved on this browser yet.'));for(const record of records){const row=node('article','');row.append(node('h3',record.title),node('p',record.status==='sending'?'Upload not confirmed — retry safely.':'Status: '+record.status));if(record.note)row.append(node('p',record.note));const button=(text,fn)=>{const b=node('button',text);b.type='button';b.onclick=()=>run(async()=>{await fn();await mine();});row.append(b);};if(record.folder)button('Retry upload',()=>send(record));button('Check status',async()=>{const data=await request(record,'GET');record.status=data.status;record.note=data.review_note||'';delete record.folder;await storage('put',record);$('message').textContent='Submission status updated.';});if(record.status!=='withdrawn')button('Withdraw',async()=>{if(!confirm('Withdraw this loadout from the library and review queue?'))return;await request(record,'DELETE');record.status='withdrawn';delete record.folder;await storage('put',record);$('message').textContent='Submission withdrawn.';});$('mine').append(row);}}
$('refresh').onclick=()=>run(async()=>{for(const record of await storage('getAll')){if(record.status==='sending'||record.status==='withdrawn')continue;const data=await request(record,'GET');record.status=data.status;record.note=data.review_note||'';await storage('put',record);}await mine();$('message').textContent='Submission statuses refreshed.';});
run(mine);
