'use strict';
const API='https://msbt-community-library.screename53.workers.dev', $=id=>document.getElementById(id), contract=communityFolderContract;
let prepared=null,shown=0,busy=false,screenshots=new Map();
const node=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;return el;};
const database=new Promise((resolve,reject)=>{const req=indexedDB.open('community-submissions',1);req.onupgradeneeded=()=>req.result.createObjectStore('submissions',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Browser storage is unavailable. Enable site storage before submitting.'));});
async function storage(method,value){const db=await database;return new Promise((resolve,reject)=>{const tx=db.transaction('submissions',method==='getAll'?'readonly':'readwrite'),request=tx.objectStore('submissions')[method](...(value===undefined?[]:[value]));tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(Error('Could not save your submission on this browser. Nothing new was uploaded.'));});}
async function run(fn){if(busy)return;busy=true;$('fields').disabled=true;try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;$('fields').disabled=false;}}
function invalidate(clear=true){if(clear)screenshots.clear();prepared=null;$('preview').hidden=true;$('consent').checked=false;}
$('source').addEventListener('input',()=>invalidate());for(const id of ['title','creator','description'])$(id).addEventListener('input',()=>{$('consent').checked=false;});
$('file').onchange=()=>run(async()=>{invalidate();const file=$('file').files[0];if(!file)return;if(file.size>contract.MAX_BYTES)throw Error('File exceeds 16 MB. Split it into smaller collections.');$('source').value=await file.text();$('message').textContent='File loaded. Choose Preview loadout.';});
$('previewButton').onclick=()=>run(async()=>{
 invalidate(false);const text=$('source').value.trim();if(new TextEncoder().encode(text).length>contract.MAX_BYTES)throw Error('Input exceeds 16 MB.');let folder;
 if(text.startsWith('{')){const data=JSON.parse(text);folder=data.folder||data;for(const key of ['title','creator','description'])if(!$(key).value&&typeof folder[key]==='string')$(key).value=folder[key];}
 else folder={version:1,folders:[],items:text.split(/\r?\n/).filter(line=>line.trim()).map((serial,i)=>({name:'Saved item '+(i+1),folder:'',serial:serial.trim()}))};
 prepared=contract.normalize({...folder,title:$('title').value,creator:$('creator').value,description:$('description').value});if(!text.startsWith('{'))await Promise.all(prepared.items.map(async item=>{const match=await CommunityImages.match(item.serial);if(match?.name)item.name=match.name.slice(0,180);}));shown=0;$('items').replaceChildren();render();$('preview').hidden=false;$('message').textContent='Review the names and codes below before submitting.';
});
function paintScreenshot(picture,item,data){picture.dataset.imageRequest='';picture.replaceChildren();const image=document.createElement('img');image.src='data:image/jpeg;base64,'+data;image.alt='Your screenshot for '+item.name;image.style.cssText='max-width:100%;max-height:360px';const remove=node('button','Remove screenshot');remove.type='button';remove.onclick=()=>{screenshots.delete(item.serial);picture.dataset.imageRequest='';picture.replaceChildren();$('consent').checked=false;CommunityImages.show(picture,item).catch(()=>{});};picture.append(image,remove);}
function render(){const end=Math.min(shown+50,prepared.items.length);for(let i=shown;i<end;i++){const item=prepared.items[i],row=node('div','');row.className='item';const label=node('label','Item '+(i+1)+' name'),input=document.createElement('input');input.value=item.name;input.maxLength=180;input.oninput=()=>{item.name=input.value;$('consent').checked=false;};label.append(input);const code=document.createElement('textarea');code.readOnly=true;code.value=item.serial;code.setAttribute('aria-label','Item '+(i+1)+' code');row.append(label,node('small',item.folder||'Folder root'),code);const picture=node('div','');row.append(picture);if(screenshots.has(item.serial))paintScreenshot(picture,item,screenshots.get(item.serial).data);else CommunityImages.show(picture,item).catch(()=>{});CommunityImages.match(item.serial).then(match=>{if(!match?.name||!picture.isConnected)return;const useName=node('button','Use GZO name: '+match.name);useName.type='button';useName.onclick=()=>{item.name=match.name;input.value=match.name;$('consent').checked=false;};row.append(useName);}).catch(()=>{});const uploadLabel=node('label','Item screenshot (optional)'),upload=document.createElement('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.onchange=()=>run(async()=>{if(!upload.files[0])return;if(!screenshots.has(item.serial)&&screenshots.size>=20)throw Error('Choose up to 20 screenshots per loadout.');const result=await CommunityImages.prepare(upload.files[0]);screenshots.set(item.serial,{id:result.id,serial:item.serial,data:result.data});paintScreenshot(picture,item,result.data);$('consent').checked=false;$('message').textContent='Screenshot ready. It will be sent with this loadout for review.';});uploadLabel.append(upload);row.append(uploadLabel); $('items').append(row);}shown=end;$('count').textContent=prepared.items.length+' items · showing '+shown;$('more').hidden=shown>=prepared.items.length;}
$('more').onclick=()=>{if(!busy)render();};
async function request(record,method){const res=await fetch(API+'/submissions'+(method==='POST'?'':'/'+record.id),{method,credentials:'omit',redirect:'error',headers:{Authorization:'Bearer '+record.secret,...(method==='POST'?{'Content-Type':'application/json'}:{})},body:method==='POST'?JSON.stringify({id:record.id,folder:record.folder}):undefined,signal:AbortSignal.timeout(60000)});const data=await res.json();if(!res.ok||!data.ok)throw Error(data.message||'Request failed.');return data;}
async function send(record){$('message').textContent='Uploading for review…';const data=await request(record,'POST');if(record.images?.length){const status=await request(record,'GET');const res=await fetch(API+'/submissions/'+record.id+'/images',{method:'POST',credentials:'omit',headers:{Authorization:'Bearer '+record.secret,'Content-Type':'application/json'},body:JSON.stringify({digest:status.digest,media_revision:status.media_revision||0,images:record.images}),signal:AbortSignal.timeout(60000)});const result=await res.json();if(!res.ok||!result.ok)throw Error(result.message||'Screenshot upload failed.');}record.status='pending';delete record.folder;delete record.images;await storage('put',record);$('message').textContent='Submitted for approval, including your screenshots. It will appear after review.';}
$('form').onsubmit=e=>{e.preventDefault();run(async()=>{if(!prepared)throw Error('Preview your loadout first.');if(!$('consent').checked)throw Error('Confirm that you want to share this loadout.');const record={id:crypto.randomUUID(),secret:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),folder:contract.normalize({...prepared,title:$('title').value,creator:$('creator').value,description:$('description').value}),title:$('title').value,status:'sending',images:[...screenshots.values()]};await storage('put',record);invalidate();try{await send(record);$('form').reset();}catch(e){throw Error(e.message+' Use Retry below to safely finish this same submission.');}finally{await mine();}});};
async function mine(){const records=await storage('getAll');$('mine').replaceChildren();if(!records.length)$('mine').append(node('p','No submissions saved on this browser yet.'));for(const record of records){const row=node('article','');row.append(node('h3',record.title),node('p',record.status==='sending'?'Upload not confirmed — retry safely.':'Status: '+record.status));if(record.note)row.append(node('p',record.note));const button=(text,fn)=>{const b=node('button',text);b.type='button';b.onclick=()=>run(async()=>{await fn();await mine();});row.append(b);};if(record.folder)button('Retry upload',()=>send(record));button('Check status',async()=>{const data=await request(record,'GET');record.status=data.status;record.note=data.review_note||'';if(!record.images?.length)delete record.folder;await storage('put',record);$('message').textContent='Submission status updated.';});if(record.status!=='withdrawn')button('Withdraw',async()=>{if(!confirm('Withdraw this loadout from the library and review queue?'))return;await request(record,'DELETE');record.status='withdrawn';delete record.folder;delete record.images;await storage('put',record);$('message').textContent='Submission withdrawn.';});$('mine').append(row);}}
$('refresh').onclick=()=>run(async()=>{for(const record of await storage('getAll')){if(record.status==='sending'||record.status==='withdrawn')continue;const data=await request(record,'GET');record.status=data.status;record.note=data.review_note||'';await storage('put',record);}await mine();$('message').textContent='Submission statuses refreshed.';});
run(mine);
